name: BUILD-PM4
on: 
  push:
    branches:
      - kr-github-actions
  #pull_request:
  #  types: [opened, reopened, synchronize, edited]
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight     
  #workflow_dispatch:
  #pull_request:
  #  branches:
  #    - main
env:
  SHA: ${{github.event.pull_request.head.sha}}
  PROJECT: ${{github.event.pull_request.head.repo.name}}
  BODY: ${{github.event.pull_request.body}}
  PACKAGE_URL: ${{github.event.pull_request.head.repo.ssh_url}}
  PACKAGE_BRANCH: ${{github.event.pull_request.head.ref}}
  MY_GITHUB_TOKEN: ${{ secrets.GH_STATUS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
  GIT_TOKEN: ${{ secrets.MY_GH_TOKEN }}
  OWNER: ${{ github.event.pull_request.head.repo.owner.login }}  
  #Other Parameters
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: us-east-1
  CI_PACKAGE_BRANCH: ${{github.event.pull_request.head.ref}}
  CI_PROJECT: ${{github.event.pull_request.head.repo.name}}
jobs:
  job1:
    name: set-init-github-status
    runs-on: ubuntu-20.04
    steps:
      - run: ls -la
      - uses: actions/checkout@v3
      - run: ls -la 
  job2:
    name: build-stm-image
    needs: job1
    runs-on: ubuntu-20.04
    env:
      # set image tag
      IMAGE_TAG: $(echo "$CI_PROJECT-$CI_PACKAGE_BRANCH" | sed "s;/;-;g") #"${CI_PROJECT}-test"
    steps:     
      - name: Push the image to ECR                
        run: |
          echo "Second Step"
  job3: 
    name: deploy-stm
    needs: job2
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: |
          ls -la
          pwd
          echo "third Step"
  job4: 
    name: run-phpunit
    needs: job2
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: |
          echo "fourth Step"
  job5: 
    name: run-benchmarks
    needs: job3
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: |
          echo "Fifth Step"
  job6: 
    name: run-cypress
    needs: job3
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: |
          echo "fourth Step"
  job7: 
    name: run-cypress-qa
    needs: job3
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: |
          echo "Sixt Step"
      
